### ISSUE TITLE
[REQUEST] - <Want to add CODE_OF_CONDUCT.md file >

### ISSUE THREAD

**Issue by sb-decoder** [bieefilled/Library#8]
### Description

Your repo has no CODE_OF_CONDUCT.md file, I want to add one

**Comment by 29deepanshutyagi** [comment]
kindly assign me this issue @bieefilled  ,i want to work on this issue

**Comment by Petsamuel** [comment]
> ### Description
> Your repo has no CODE_OF_CONDUCT.md file, I want to add one
> 
> ### Basic Example
> _No response_

this issue will be assigned to you

**Comment by bieefilled** [comment]
@29deepanshutyagi kindly look for other issues
